web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./code:/code
        - ./nginx:/etc/nginx/conf.d/
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./code:/code
